### ISSUE TITLE
Has it been tested with the latest Microtik ?

### ISSUE THREAD

**Issue by soamz** [grafjo/mikrotik-hotspot-webinterface#1]
Hi, is the project still alive ?
We would like to test it then.

**Comment by grafjo** [comment]
Hi @soamz,

I didn't test it with the current RouterOS 6.32.2 release - it should work with 6.x.

**Comment by soamz** [comment]
Okay is there a demo site or video, where we can see how it works before we download ?

**Comment by grafjo** [comment]
Not at the moment. It's based on the RouterOS default hotspot html pages using bootstrap

**Comment by soamz** [comment]
Oh, so it just the hotspot html template ?

**Comment by grafjo** [comment]
yes it is
